# Generated by Django 5.x on project bootstrap.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('scheduled', 'Scheduled'),
                            ('sending', 'Sending'),
                            ('sent', 'Sent'),
                            ('failed', 'Failed'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                (
                    'platform',
                    models.CharField(
                        choices=[
                            ('x', 'X / Twitter'),
                            ('facebook', 'Facebook'),
                            ('instagram', 'Instagram'),
                            ('linkedin', 'LinkedIn'),
                            ('tiktok', 'TikTok'),
                        ],
                        max_length=20,
                    ),
                ),
                ('handle', models.CharField(max_length=120)),
                ('access_token', models.TextField(help_text='Store securely in production (vault/secret manager).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'unique_together': {('platform', 'handle')}},
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deliveries',
                        to='broadcast.socialaccount',
                    ),
                ),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deliveries',
                        to='broadcast.messagecampaign',
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
