# Generated by Django 5.2.11 on 2026-02-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecampaign",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="messagecampaign",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="messagecampaign",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("ai_news", "AI News")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="messagecampaign",
            name="task_mode",
            field=models.CharField(
                choices=[("manual", "Manual Task"), ("automated", "Automated Task")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
